// <auto-generated />
using DigiAssistant.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiAssistant.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiAssistant.Core.Entities.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErrorCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Solution1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SolutionPhoto1")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("ErrorCategoryId");

                    b.ToTable("Errors");
                });

            modelBuilder.Entity("DigiAssistant.Core.Entities.ErrorCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yazılımsal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Donanımsal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ağ"
                        });
                });

            modelBuilder.Entity("DigiAssistant.Core.Entities.Error", b =>
                {
                    b.HasOne("DigiAssistant.Core.Entities.ErrorCategory", "ErrorCategory")
                        .WithMany("Errors")
                        .HasForeignKey("ErrorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErrorCategory");
                });

            modelBuilder.Entity("DigiAssistant.Core.Entities.ErrorCategory", b =>
                {
                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
